version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.11
        commands:
            - pip install --upgrade pip
            - pip install -r requirements.txt pylint
    pre_build:
        commands:
            - python --version
            - pylint $CODEBUILD_SRC_DIR/*.py
            - pylint --disable=C0103 $CODEBUILD_SRC_DIR/estateProj/*.py
            - pylint --disable=E1101,C0301,R0903,W0612,R1705 $CODEBUILD_SRC_DIR/listings/*.py
artifacts:
    files:
        - '**/*'