# Generated by Django 4.2.10 on 2024-03-07 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('single_family_detached', 'Single-family detached'), ('bungalow', 'Bungalow'), ('ranch_style', 'Ranch-style'), ('cottage', 'Cottage'), ('apartment', 'Apartment'), ('duplex', 'Duplex'), ('triplex', 'Triplex'), ('penthouse', 'Penthouse'), ('terrace_house', 'Terrace House'), ('studio_apartment', 'Studio Apartment'), ('semi_detached', 'Semi-detached'), ('mansion', 'Mansion')], max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale')], max_length=10)),
                ('image', models.ImageField(upload_to='images/')),
                ('image_url', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
