# Generated by Django 4.2.10 on 2024-02-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
