# Generated by Django 4.2.10 on 2024-02-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_house_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='image_url',
        ),
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='house_images/'),
        ),
    ]
