# Generated by Django 4.2.10 on 2024-02-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_house_image_url_house_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='image',
        ),
    ]
