# Generated by Django 4.2.10 on 2024-03-09 17:22

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_house_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='country',
            field=django_countries.fields.CountryField(default='Ireland', max_length=2),
        ),
    ]
