# Generated by Django 4.2.10 on 2024-03-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_house_address_house_contact_house_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(choices=[('single_family_detached', 'Single-family detached'), ('bungalow', 'Bungalow'), ('ranch_style', 'Ranch-style'), ('cottage', 'Cottage'), ('apartment', 'Apartment'), ('duplex', 'Duplex'), ('triplex', 'Triplex'), ('penthouse', 'Penthouse'), ('terrace_house', 'Terrace House'), ('studio_apartment', 'Studio Apartment'), ('semi_detached', 'Semi-detached'), ('mansion', 'Mansion')], max_length=100),
        ),
    ]
